syntax = "proto3";

package cluster;

service ClusterApi {
    rpc CreatePod(CreatePodRequest) returns (PodId);
    rpc GetPod(PodId) returns (Pod);
    rpc DeletePod(PodId) returns (DeletePodResponse);
    rpc ListPods(ListPodsRequest) returns (ListPodsResponse);
    rpc RegisterNode(RegisterNodeRequest) returns (NodeId);
    rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse);
    rpc GetNode(NodeId) returns (Node);
    rpc ListNodes(ListNodesRequest) returns (ListNodesResponse);
    rpc ReportPodStatus(PodStatus) returns (Ack);
}

message CreatePodRequest {
    string name = 1;
    string namespace = 2;
    repeated ContainerSpec containers = 3;
}

message PodId{
    string pod_id = 1;
}

message DeletePodResponse {
    bool success = 1;
}

message ListPodsRequest {
    string namespace = 1;
}

message ListPodsResponse {
    repeated Pod pods = 1;
}

message RegisterNodeRequest {
    string addr = 1;
    uint64 cpu_t = 2;
    uint64 mem = 3;
    map<string, string> labels = 4;
}



message HeartbeatRequest {
    string node_id = 1;
    uint64 cpu_t = 2;
    uint64 mem = 3;
}

message HeartbeatResponse {
    bool accepted = 1;
}

message NodeId{
    string node_id = 1;
}

message ListNodesRequest {}

message ListNodesResponse {
    repeated Node nodes = 1;
}

message Ack {
    bool success = 1;
}

message Pod {
    string id = 1;
    string name = 2;
    string namespace = 3;
    PodSpec spec = 4;
    PodStatus status = 5;
    string phase = 6;
    string node_id = 7;
}

message PodSpec {
    repeated ContainerSpec containers = 1;
}

message ContainerSpec {
    string name = 1;
    string image = 2;
    repeated string command = 3;
    repeated string args = 4;
    uint64 cpu_t = 5;
    uint64 mem = 6;
}

message PodStatus {
    string pod_id = 1;
    string phase = 2;
    string mssg = 3;
    repeated ContainerStatus statuses = 4;
}

message ContainerStatus {
    string name = 1;
    bool ready = 2;
    int32 ecode = 3;
    string mssg = 4;
}

message Node {
    string id = 1;
    string addr = 2;
    Resources cap = 3;
    Resources availib = 4;
    string status = 5;
    map<string, string> labels = 6;
    int64 last_ping = 7;
}

message Resources {
    uint64 cpu_t = 1;
    uint64 mem = 2;
}
